#!/usr/bin/env python

from ase.io import read
import os
import sys
'''
def new_header(fname):
    with open(fname,'r') as fn:
        lines = fn.readlines()
    with open(fname,'w') as fw:
        cline = ''
        for i, line in enumerate(lines):
            if not i:
                cline = line
            if 0<=i<=3:
                fw.write(lines[i+1])
            elif i==4:
                fw.write(cline)
            else:
                fw.write(line)
'''

basename = sys.argv[1].split('.')[0]
suffix = sys.argv[1].split('.')[-1]

if not os.path.isdir(basename):
    os.makedirs(basename)
if suffix == 'xml':
    a = read(sys.argv[1],format='vasp-xml',index=':')
else:
    if suffix not in ['data','dump']:
        a = [read(sys.argv[1])]
if len(sys.argv)==3:
    ntv = int(sys.argv[2])
else:
    ntv = 1

for ind, a_i in enumerate(a):
    if not (ind+1)%ntv:
        pn = '%s/%i.poscar'%(basename,ind)
        a_i.write(pn)
        #new_header(pn)

