#!/usr/bin/env python

import os
import shutil
import numpy as np

def get_maxnumber(names):
    numbers = []
    for name in names:
        numbers.append(int(name.split("-")[0]))
    return max(numbers)


def read_info(info_path):
    with open(info_path,"r") as ifp:
        lines = ifp.readlines()
    res = float(lines[-1].strip().split()[-1])
    return res


def move_rename(nn_path,nnpool_path):
    filenames = os.listdir(nn_path)
    for ind, filename in enumerate(filenames):
        namesplit = filename.split(".")
        if len(namesplit) == 3 and namesplit[-1] == "nn":
            filenames[ind] = ".".join(namesplit[slice(0,3,2)])
        absfn  = os.path.join(nn_path,filename)
        abspfn = os.path.join(nnpool_path,filenames[ind])
        shutil.copyfile(absfn,abspfn)


def build_pool():
    os.makedirs("nn_pool/ensemble")
    os.makedirs("nn_pool/best")
    n = get_maxnumber(os.listdir("04-Train"))
    errors = np.zeros(n)
    for i in range(n):
        nn_path = os.path.join(os.getcwd(),\
                "04-Train/%i-train/1_nnpots"%(i+1))
        nnpool_path = os.path.join(os.getcwd(),\
                "nn_pool/ensemble/%i-nn"%(i+1))
        os.makedirs(nnpool_path) 
        move_rename(nn_path,nnpool_path)
        errors[i] = read_info(os.path.join(nn_path,"info"))
    nn_best_path = os.path.join(os.getcwd(),\
            "04-Train/%i-train/1_nnpots"%(np.argmin(errors)+1))
    nnpool_best_path = os.path.join(os.getcwd(),"nn_pool/best")
    move_rename(nn_best_path,nnpool_best_path)


if os.path.exists("nn_pool"):
    shutil.rmtree("nn_pool")
    build_pool()
else:
    build_pool()
