#!/usr/bin/env python

import sys
import os
import numpy as np

path = sys.argv[1]

test_error = []
for na in os.listdir(path):
    nn_path = os.path.join(path,na,'1_nnpots')
    nn_info = os.path.join(nn_path,'info')
    with open(nn_info,'r') as nnf:
        _ = nnf.readline()
        _ = nnf.readline()
        last_line = nnf.readline()
        test_error.append(float(last_line.split()[-1]))
test_error = np.array(test_error)
print("Average test error : %e eV/atom"%(np.sum(test_error)/len(test_error)))
